version: 1.0.{build}

image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  webapp_folder: .\testAppVeyor
  webapp_proj: $(webapp_folder)\testAppVeyor.csproj
  webapp_package: testAppVeyor.$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)
  

before_build:
  - ps: dotnet restore

build:
  verbosity: minimal
  project: testAppVeyor.sln

after_build:
  - ps: .\package.ps1 -projectPath $env:webapp_proj -packageName $env:webapp_package -absoluteRepoDirectory $env:APPVEYOR_BUILD_FOLDER

artifacts:
  - path: '**\$(webapp_package).zip'
